# Generated by Django 5.2 on 2025-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalimage',
            name='file_path',
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='image_file',
            field=models.ImageField(null=True, upload_to='medical_images/%Y/%m/%d/'),
        ),
    ]
